version: '3'

services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - 5080:80
    networks:
          - dddnet
    
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    ports:
      - 7209:80
    networks:
      - dddnet
    
  product:
    container_name: product
    build:
      context: .
      dockerfile: ./Product/Dockerfile
    ports:
      - 5194:80
    networks:
    - dddnet

  authdb:
    container_name: AuthSqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "8001:1433"
    environment:
      SA_PASSWORD: "LolKek123"
      ACCEPT_EULA: "Y"
      DB: AuthProgZona
    networks:
      - dddnet
networks:
  dddnet:
      