services:
  auth:
    container_name: auth
    build:
      context: ..
      dockerfile: ./auth/Dockerfile
      target: final
    ports:
      - 7258:5080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APP_PORT=7258
    depends_on:
      - db
  gateway:
    container_name: gateway
    build:
      context: ..
      dockerfile: ./Gateway/Dockerfile
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7209:5185
    depends_on:
      - db
  product:
    container_name: product
    environment:
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ..
      dockerfile: ./Product/Dockerfile
      target: final
    ports:
      - 7091:5194
    depends_on:
      - db
  
  db:
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "LolKek123"
      ACCEPT_EULA: "Y"
      USER: myuser
      DB: AuthProgZona